### ISSUE TITLE
SteamBanChecker with Overwatch

### ISSUE THREAD

**Issue by ghost** [IceQ1337/SteamBanChecker#14]
Hello, I added the Telegram API (messaging-api-telegram) on the overwatch bot, to send a message in Telegram (/add steamid64)

Example: 
client.sendMessage(chat_id, '/add ' + sid.getSteamID64());

the message is sent but the bot does not answer, on the other hand if I send me the message the bot answers, I think that SteamBanChecker does not take into account the answers of the bots.

My discord: soso#1000

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/62655434/77823357-e38c9e80-70fa-11ea-9a54-9193f1af9cd5.png)

**Comment by IceQ1337** [comment]
What exactly are you trying to achieve?  
And do you get any error messages in the console?

**Comment by ghost** [comment]
I have an overwatch bot, and I get the steamid64 of the person, I would like it to send in the telegram group automatically /add XXXX

XXXX = steamid64

Example:

I have this guy in Overwatch '76561197991558078', so sid.getSteamID64() = 76561197991558078, so if I use 'client.sendMessage(chat_id, '/add ' + sid.getSteamID64());' he send '/add 76561197991558078' in the telegram for add automaticaly in the data for have a tracker on all guys I overwatch, but the SteamBanChecker don't add the steamid if i send him with my account not with the bot it's work.


I have no errors on the console

**Comment by IceQ1337** [comment]
That is most-likely because the Telegram-Bot from your OverwatchChecker does not have "access" to the SteamBanChecker. You could try sending a `/request` from the OC to your SBC and accepting it. I don't know if it's any different with bots, but it should work just fine and the bot should be in your userlist `(/users)` afterwards.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/62655434/77826778-b5ff1f80-7111-11ea-96eb-fc2e097c72e8.png)

I can't pm a bot with a bot, how can I add manually in userlist ?

Do you have discord? I make a screenshare for show you maybe ?

**Comment by IceQ1337** [comment]
This is a bit tricky because the script is not designed for that. Anyway, I think there are two ways to achieve this. First of all, you would need to get your bots chatID (assuming that bots have chatIDs like users) via Telegram-Web-API. Then, you want a friend (or different telegram account) to request access and accept it. You can then change the chatID and the username in the `users.db`. Another way would be to call the `addUser` function with the bots chatID in the server.js after the database has initialized in line 8. It would look something like `Database.addUser(chatID, botName)`.

**Comment by ghost** [comment]
Even if I add the bot in user.db, it doesn't work
![image](https://user-images.githubusercontent.com/62655434/77828501-1d21d180-711c-11ea-9b19-8b32449794d4.png)

I think with your script a bot can't use the command maybe? I don't know

**Comment by IceQ1337** [comment]
You could try adding a ``console.log(`UserID: ${userID} - Username: ${userName}`);`` in line 29 of `modules/Telegram.js` in order to check if you have the right userID of the bot in your `users.db`. If there isn't any userID, there is currently no way to achieve this in a proper way, because the script isn't made for that and only works with userIDs and chatIDs.

**Comment by ghost** [comment]
I just did what you told me, I have 3 people, twice me and once a friend, but normally I should have once me, once the bot, once my friend.
![image](https://user-images.githubusercontent.com/62655434/77828884-77239680-711e-11ea-8951-ff6f8da56ea1.png)

![image](https://user-images.githubusercontent.com/62655434/77828903-94586500-711e-11ea-9727-6f4f903103e1.png)

Maybe with a selfbot ? But I have no idea how to make a selfbot

**Comment by IceQ1337** [comment]
I double-checked this and it seems like bots can't receive messages from other bots.  
See: https://core.telegram.org/bots/faq#why-doesnt-my-bot-see-messages-from-other-bots

**Comment by ghost** [comment]
RIP
