### ISSUE TITLE
[IDEA] Discord instead of Telegram

### ISSUE THREAD

**Issue by ghost** [IceQ1337/SteamBanChecker#15]
Hi again xD,

Do you think you can make a version discord? 
I recommend you using [discord.js](https://discord.js.org/#/) for [nodejs](https://www.npmjs.com/package/discord.js)

You can send a [embed ](https://discordjs.guide/popular-topics/embeds.html#embed-preview)beautiful 

https://discord.js.org/#/docs/main/stable/class/MessageEmbed?scrollTo=setImage

Cordially. 🙏

**Comment by ghost** [comment]
Hi, do you have Discord?

**Comment by IceQ1337** [comment]
Yes. `IceQ1337#6514`

**Comment by IceQ1337** [comment]
This has already been implemented and will soon be made publicly available in another repository, but since I have received compensation for this from several people and I am not a rip-off, I am giving the project some additional time until publication. I will probably publish the script towards the end of the month.
