### ISSUE TITLE
Screenshots missing & sometimes possible to add one account multiple times.

### ISSUE THREAD

**Issue by ghost** [IceQ1337/SteamBanChecker#16]
`
[Mon, 18 May 2020 16:00:32 GMT] [INFO] [SteamAPI] Ban > Profile: 76561199057405575 Type: game
[Mon, 18 May 2020 16:00:32 GMT] [ERROR] [Screenshot] saveProfile > Error: PhantomJS exited with return value 1
`
Notifications of bans are just fine. but screenshots are missing.
Any idea/help?

Edit: installed new webshot-node and phantomjs-prebuild came with it, will see if it works this time, till then, i need ideas.

Edit2: I just found out that you can add some accounts multiple times, with others you get the "already on the list" message. 
Example: i can `/add https://steamcommunity.com/profiles/76561199046123337/` that profile unlimited times, but i can't seem to add my profile multiple times. picture for clearing this a bit up
the profile i can add multiple times:
![Screensh1111ot_1](https://user-images.githubusercontent.com/39536166/82287114-b55f6880-999f-11ea-9e55-081ccd5ac582.png)
my profile:
![Screenshot_1](https://user-images.githubusercontent.com/39536166/82287242-0cfdd400-99a0-11ea-9d16-af34c76b8b5c.png)

**Comment by IceQ1337** [comment]
Regarding Screenshots:
[Dependencies](https://github.com/IceQ1337/SteamBanChecker#dependencies)

About Duplicates:
I was able to reproduce this and applied a [fix](https://github.com/IceQ1337/SteamBanChecker/commit/bdd31e53231094ed48f8fabbdc2ac2a93b26f641) for this issue. There is no need to edit the database, because the duplicate entries were getting saved as one entry regardless.

Thank you for reporting this issue.
