### ISSUE TITLE
Suggestion: removing/deleting profiles & /profiles command

### ISSUE THREAD

**Issue by ghost** [IceQ1337/SteamBanChecker#17]
It would be nice if you could remove accounts from the list, and just view them, much like the /users command, but with the steam accounts. You could also see who added it, when, and if it's banned or not, then you could remove it if you decide you don't want that account to be there in the database.

Edit: users could see their accounts, master could select user then see his/her accounts.

**Comment by IceQ1337** [comment]
1. In the initial version(s) of this script there was a function to remove/delete profiles, but this was removed due to incompatibilities and was never added again. If I have time for it, I may re-implement this function.

2. Even though it's pretty cool to add new commands and features, I can't think of a good use-case that makes this feature worth the time, but I can think of several reasons not to implement it.
- In the first place, only users that are/whose behaviour is trusted should be added
- The master shouldn't care about profiles added by different users
- Interaction with banned profiles is unnecessary. They only still exist for statistics.
- A long list with hundreds of profiles would be very difficult (if not impossible) to manage
- The list would only contain illegible profile-ids and differentiation would be very difficult
- ...

Also, the Telegram version does not save the current time when adding new profiles and it also doesn't save the user who added the profile. This user is usually the first entry in the "userlist", but this is not always the case.
