### ISSUE TITLE
Screenshots are not consistent

### ISSUE THREAD

**Issue by ghost** [IceQ1337/SteamBanChecker#18]
```

[Tue, 19 May 2020 11:37:51 GMT] [INFO] [SteamAPI] Ban > Profile: 76561199059152009 Type: game
[Tue, 19 May 2020 11:37:51 GMT] [ERROR] [Screenshot] saveProfile > Error: PhantomJS exited with return value 1

```
Nothing changed in between the bans ,few just happened to not get screenshotted.
![Screenshot_2](https://user-images.githubusercontent.com/39536166/82322590-0cccfb00-99d7-11ea-8557-e23a8cd2a0fc.png)
![Screenshot_3](https://user-images.githubusercontent.com/39536166/82326472-2bce8b80-99dd-11ea-8517-10231d08cc9f.png)
(Migth be the russian letters?)
![Screenshot_4](https://user-images.githubusercontent.com/39536166/82398851-18aad280-9a54-11ea-88ce-ea38ea624d66.png)
![Screenshot_5](https://user-images.githubusercontent.com/39536166/82398868-22343a80-9a54-11ea-9d9d-c5483a041df0.png)
(It was not the russian letters.)

**Comment by ghost** [comment]
Sad thing is that no matter how hard i try to reproduce this issue in a "debug" state, i can't, it screenshots it, saves it and yes, it works. I have no idea why does it happen only when it is running with everything, i will try newer webshote-node and phantomJS, and see if that solves it.

Edit: newer version of webshot-node and phantomJS does absolutely nothing...

**Comment by ghost** [comment]
I made a duct tape like solution.
```JavaScript
var sleep = require('system-sleep');


        if (Config.Screenshot.saveScreenshot) {
            Screenshot.saveProfile(profileURL, player.SteamId).then((imagePath) => {
                if (imagePath && Config.Screenshot.sendScreenshot) {
                    Screenshot.saveProfile(profileURL, player.SteamId)
                    sleep(5*1000);
                    Telegram.sendPhoto(message, imagePath, users);
                } else {
                    Telegram.sendMessage(message, users);
                }
            }).catch((err) => {
                Utility.log('ERROR', 'Screenshot', 'saveProfile', err);
                Telegram.sendMessage(message, users);
            });
```
Looks like shit, but in the tests i did it worked so i can't say anything bad about it, maybe that it delays the messages by 5 seconds, but messages can be delayed anyway because of the time it checks them.

Edit:
I added sleep because i tought that it has no time to get the screenshot and thats why it fails.
I tought of this because i had a screenshot that only had the top half.
I will do more testing, but this seems like a valid theory to me, as it works flawlessly with the sleep integrated now.
I will get a few more accounts banned to see if it really solved it.

**Comment by IceQ1337** [comment]
I am unable to reproduce this error myself. 

> 
> 
> Edit: newer version of webshot-node and phantomJS does absolutely nothing...

All versions in the package.json are up-to-date and there is no "newer version of webshot or phantomJS" as phantomJS development has been suspended and webshot has not been updated for a long time (because it works with the last version of phantomJS), which is why i use a forked module that uses an updated dependency in order to get webshot to work properly on current Node.js versions.


> 
> 
> I made a duct tape like solution.
> 

There may is an issue with taking screenshots (server connectivity, etc.), but your "solution" does literally nothing other than reducing the scripts performance. Within the function that takes a screenshot, which is a promise that returns the image path of the taken screenshot in the first place, you are just calling the same function without handling the response or catching errors. The only effect this creates is that you are saving the image twice and if it fails, your script will crash with an unhandled error.

Furthermore, the use of sleep functions in any type of program is extremely inefficient, a sign for poorly-written and designed projects and should be avoided under all circumstances. In this case, it doesn't even make sense to use it, since the function to send the message is only called after the screenshot has already been taken. You should read about asynchronous code and promises if you are interested in js programming.

**Comment by ghost** [comment]
"Duct tape like", it was not meant to be the perfect code.
Reduced performance is still better than something that does not work.
(It might be an issue on my end)
Catching errors if any happen is pretty easy tho, so if it crashes anytime soon, i will be sure to "update" it.
Till then, this is the best idea i have atm, i'm just trying to figure out whats causing the problem.
I will post an update if this "fix" fails, but now, it seems to work fine.

Picture of a ban with working screenshot after my fix, but a singular success does not mean anything.
![Screenshot_6](https://user-images.githubusercontent.com/39536166/82472866-1171dc00-9ac9-11ea-8310-935a83673c13.png)

As for "updating" phantomJS and webshot-node, i never used node before so i did not know what would be the response if i tried to update it, but it said updated, and i took it for granted, again, sorry.

I'm curious, how did you try to reproduce the error?
Did you try and get accounts banned, or just simplifying the code and running it?
Because i tried that, and it worked every time, it only fails when it's "live".
Thanks for any help.

**Comment by IceQ1337** [comment]
> Reduced performance is still better than something that does not work.

Sorry, but your changes make the problem you have even worse. Instead of just taking a screenshot twice and hoping for the best, you should focus on figuring out why the original function sometimes doesn't work in the first place. If I was able to reproduce this error, I would check if the screenshot that didn't get send via Telegram actually exists on disk, check the logs (for errors like the one in your opening post) and then start logging everything around these two involved functions for example.

I mean, if your changes work for you, feel free to use it, but they don't help at troubleshooting.

> (It might be an issue on my end)

Nobody I know has reported something like this, so I assume that it actually is on your end. I think there is a known problem where webshot sometimes doesn't wait for the page to load completely, but mostly it's the operating system/server that causes it (e.g. due to a bad internet connection). However, this would not explain why no screenshot is taken at all. This can only be investigated by error logs etc.

> I'm curious, how did you try to reproduce the error?

Neither me, nor other people using either this or a similar, currently private, version are experiencing this or similar issues. In addition, i can just mark banned profiles as not banned in the database file so that the script immediately sends a notification about them after launch.

---

The following information could help at troubleshooting.

1. Which system/OS is used?  
2. Which Node.js and NPM version is used/installed?
  `node -v` & `npm -v`
3. Is there any additional information in the error/server log?
  `e.g. [ERROR] [Screenshot] saveProfile > Error: PhantomJS exited with return value 1`
4. Do the missing screenshots exist on disk?

**Comment by ghost** [comment]
After trying out what you said about marking banned profiles, to get checked again, all of the screenshots came through. Again, i don't know why it only happens sometimes, and only on "realtime" bans.
\
1.
`Debian GNU/Linux 10 (buster) x86_64 `
`Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
2. 
`Node: v10.19.0`
`NPM: 5.8.0`
I updated NPM and Node, same case, sometimes works, sometimes not.
`New Node: v13.14.0`
`New NPM: v6.14.5`
3. No, just the one i originally posted.
`[ERROR] [Screenshot] saveProfile > Error: PhantomJS exited with return value 1`
4. No, when they are missing they are not present on the disk.
